name: Build the code
on:
 push:
  branches:
   - master    
jobs:
 build-job:
  strategy:
   matrix:
    operating-system: ['ubuntu-latest', 'windows-latest']
    node_version: ['14','16','18']
  runs-on: ${{ matrix.operating-system }}
  steps:
   - name: Clone the code 
     uses: actions/checkout@v3 
   - name: Install nodejs 
     uses: actions/setup-node@v3
     with: 
      node-version: ${{ matrix.node_version }}
   - name: install dependencies
     run: npm ci
